### ISSUE TITLE
feature request: add original url and date time of conversion

### ISSUE THREAD

**Issue by Gys** [NiklasGollenstede/epub-creator#12]
Hi

Would be nice to have the original url and date of conversion to be inserted into the contents. Maybe as a footer on the last page.

The url to always be able to go back to the original text and website. The date helps to get a sense when the article was relevant, which is useful for newspaper articles.

That might also be a good opportunity to additionally add a reference to this addon ;-)

**Comment by guenam** [comment]
Hi,
I think this is indeed a very good idea. And since i share my epub articles, a mention such as "this epub was created from a webpage using the epub-creator on Firefox", or something like that, would both promote Firefox and your extension.
In all cases, thanks a lot for this extension, it's super useful.
Best regards.

**Comment by ghost** [comment]
Hi @Gys, I agree with you but I just realized that the original url is already on the top left of the epub.

**Comment by NiklasGollenstede** [comment]
The URL is/was was indeed already there, but the date should be there and was missing.
I added an ISO date (YYYY-MM-DD, internationally the least ambiguous format) next to the domain/URL.
