### ISSUE TITLE
Incomplete result file

### ISSUE THREAD

**Issue by brlin-tw** [NiklasGollenstede/epub-creator#5]
I tried to convert [this webpage](http://www.netbits.us/docs/stunnel_rsync.html), with the following markup:

```html
<HTML><HEAD><TITLE>Rsync + Stunnel 4.x</TITLE></HEAD>
<BODY>
<H1>Rsync + Stunnel 4.x</H1>
<H2>Contents</H2>
<UL>
<LI><a href="#purpose">Purpose / Overview</a></LI>
<LI><a href="#source1">Building the Sources I</a></LI>
<LI><a href="#cert">Generating Certs</a></LI>
<LI><a href="#source2">Building the Sources II</a></LI>
<LI><a href="#stunnel">Configuring Stunnel</a></LI>
<LI><a href="#rsync">Configuring Rsync</a></LI>
<LI><a href="#firewall">Firewall</a></LI>
<LI><a href="#testing">Testing</a></LI>
<LI><a href="#credits">Credits</a></LI>
<LI><a href="#todo">TODO</a></LI>
</UL>
<H2><a name="purpose">Purpose / Overview</H2>
<blockquote>
<P>
A while back I went to a great <a href="http://www.tclug.org/">TCLUG<a/> meeting with Mick Bauer giving the main presentation.
I was impressed enough with his presentation to purchase a copy of his book: <a href="http://www.oreilly.com/catalog/bssrvrlnx/">Building Secure Servers
with Linux</a>.  I also enjoy his Paranoid Penguin security related columns in the <a href="http://www.linuxjournal.com/">Linux Journal</a>.
<p>
One of Mick's columns and a portion of his book deal with setting up stunnel to tunnel rsync over
an SSL encrypted connection.  Unfortunately, I had a heck of a hard time getting this to work because
Mick's documentation examples rely heavily on tcp-wrappers and Stunnel version 3.x syntax.  Stunnel 4.x
has been stable for a long time and I always like to have my software up to date, so I wrote this
documentation to record my solution to this problem in the hopes that someone may find it useful and so I can
remember exactly what I did when I need to set this up again.  If you find any errors or omissions, please
feel free to <a href="http://www.netbits.us/contact.php">contact</a> me.
<p>
All right then, it's go time.
</blockquote>
<H2><a name="source1">Building the Sources I</H2>
<blockquote>
As much as I like certain un-named Linux distros
```

which ends up like this in the converted file:

```html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<title>Rsync + Stunnel 4.x</title>
	</head>
	<body>
<div xmlns="http://www.w3.org/1999/xhtml" class="container">
	<div class="header reader-header">
		<a class="domain reader-domain" href="http://www.netbits.us/docs/stunnel_rsync.html">netbits.us</a>
		<h1 class="reader-title">Rsync + Stunnel 4.x</h1>
		<div class="credits reader-credits"></div>
	</div>
	<hr /><div class="content"><div class="page"><div><a>
As much as I like certain un-named Linux distros
```

A significant part of the text is missing.  
Version: 0.5.5

**Comment by NiklasGollenstede** [comment]
This is a problem with Mozilla's [Readability.js](https://github.com/mozilla/readability). Let me quote from the description/readme (of this extension):

> What you get & **Troubleshooting**:
> * For general web pages, Mozilla's Readability.js is used to extract the content. Since that is the same software component used by Firefox to generate the Reader view, the result should generally be the same as well. [...] If parts of the website are missing in the book, please check whether they show up in the reader mode. If not, there is little I can change about that.

Sometimes the problem is, that the version of Readability.js used in this extension is older than the one Firefox itself uses. 
The stuff that's missing in the HTLM snippets above is also missing in Firefox 72's Reader View.

I don't know why Readability.js doesn't pass this very basic HTML on 1:1, but that is a problem that you should report with [Readability.js](https://github.com/mozilla/readability).

If/when they resolved it, feel free to inform me so I update this extension with a new version including their fix.

---

An alternative solution to this problem (Readability.js not performing well on very basic text pages, like man pages), which has come up before, would be to, when creating a book, offer the option to choose an extraction mode, with "pass through" as one choice.
But that requires actual UI, which I don't see when I will have the tome to build.
And really, Readability.js should just not suck at this ...

**Comment by brlin-tw** [comment]
Thanks!  I've forwarded the issue to [Missing beginning paragraphs (www.netbits.us) · Issue #574 · mozilla/readability](https://github.com/mozilla/readability/issues/574).

**Comment by allentiak** [comment]
@NiklasGollenstede Maybe you should keep this bug open until upstream resolves the problem?
